import "../_assets/css/style.scss";
import { Header } from "../_components/organisms/header/Header";
import { Footer } from "../_components/organisms/footer/Footer";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
